[supervisord]
nodaemon=true
logfile=/home/user/workspace/logs/supervisord.log
pidfile=/home/user/workspace/logs/supervisord.pid
childlogdir=/home/user/workspace/logs

[unix_http_server]
file=/home/user/workspace/logs/supervisor.sock

[supervisorctl]
serverurl=unix:///home/user/workspace/logs/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:mariadb]
command=/usr/sbin/mariadbd --defaults-file=/home/user/workspace/conf/my.cnf
priority=100
autostart=true
autorestart=true
stdout_logfile=/home/user/workspace/logs/mariadb.log
redirect_stderr=true

[program:redis]
command=/usr/bin/redis-server /home/user/workspace/conf/redis.conf
priority=100
autostart=true
autorestart=true
stdout_logfile=/home/user/workspace/logs/redis.log
redirect_stderr=true

[program:backend-web]
command=/opt/venv/bin/python3 app/backend-web/main.pyc
directory=/home/user/workspace/app
priority=200
autostart=true
autorestart=true
startsecs=10
environment=WEB_DIR="/home/user/workspace/app/web"
stdout_logfile=/home/user/workspace/logs/backend-web.log
redirect_stderr=true

[program:websocket]
command=/opt/venv/bin/python3 app/websocket/main.pyc
directory=/home/user/workspace/app
priority=300
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/home/user/workspace/logs/websocket.log
redirect_stderr=true

[program:scheduler]
command=/opt/venv/bin/python3 app/scheduler/main.pyc
directory=/home/user/workspace/app
priority=300
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/home/user/workspace/logs/scheduler.log
redirect_stderr=true
